---
- name: download
  get_url: url=https://codeload.github.com/kyuupichan/electrumx/tar.gz/1.0.17 dest=/tmp mode=0440
- name: extract
  command: tar zxvf electrumx-1.0.17.tar.gz chdir=/tmp
- name: setup
  command: /usr/bin/python3.6 ./setup.py install chdir=/tmp/electrumx-1.0.17
- name: copy
  command: cp /tmp/electrumx-1.0.17/contrib/systemd/electrumx.service /etc/systemd/system/electrumx.service
- name: template setup
  template: src="templates/electrumx.conf.j2" dest="/etc/electrumx.conf" owner=root group=root
