---
- name: download
  get_url: url=https://codeload.github.com/kyuupichan/electrumx/tar.gz/{{ electrumx_version }} dest=/tmp mode=0440
- name: extract
  unarchive: src=/tmp/electrumx-{{ electrumx_version }}.tar.gz dest=/tmp copy=no
- name: install
  command: /usr/bin/python3.6 ./setup.py install chdir=/tmp/electrumx-{{ electrumx_version }}
- name: electrumx systemd setup
  template: src="templates/electrumx.service.j2" dest="/etc/systemd/system/electrumx.service" owner=root group=root
- name: electrumx template setup
  template: src="templates/electrumx.conf.j2" dest="/etc/electrumx.conf" owner=root group=root
