---
- name: download
  get_url: url=https://codeload.github.com/kyuupichan/electrumx/tar.gz/{{ electrumx_version }} dest=/tmp mode=0440
- name: extract
  unarchive: src=/tmp/electrumx-{{ electrumx_version }}.tar.gz dest=/tmp copy=no
- name: pip install
  pip: name={{ item }} executable=pip3.6
  with_items:
   - uvloop 
- name: install
  command: /usr/bin/python3.6 ./setup.py install chdir=/tmp/electrumx-{{ electrumx_version }}
- name: electrumx systemd setup
  template: src="templates/electrumx.service.j2" dest="/etc/systemd/system/electrumx.service" owner=root group=root
- name: electrumx template setup
  template: src="templates/electrumx.conf.j2" dest="/etc/electrumx.conf" owner=root group=root
- name: electrumx copy script
  command: cp compact_history.py /usr/local/bin chdir=/tmp/electrumx-{{ electrumx_version }}
- name: electrumx autocompact script
  template: src="templates/electrumx_autocompact.sh.j2" dest="/usr/local/bin/electrumx_autocompact.sh" owner=root group=root mode=0755
- name: electrumx cron script
  template: src="templates/electrumx_cron.j2" dest="/etc/cron.daily/electrumx" owner=root group=root mode=0700
