---
- name: download
  get_url: url=https://codeload.github.com/kyuupichan/electrumx/tar.gz/1.0.17 dest=/tmp mode=0440
- name: extract
  unarchive: src=/tmp/electrumx-1.0.17.tar.gz dest=/tmp copy=no
- name: install
  command: /usr/bin/python3.6 ./setup.py install chdir=/tmp/electrumx-1.0.17
- name: systemd config copy
  command: cp /tmp/electrumx-1.0.17/contrib/systemd/electrumx.service /etc/systemd/system/electrumx.service
- name: electrum template setup
  template: src="templates/electrumx.conf.j2" dest="/etc/electrumx.conf" owner=root group=root
