---
- hosts: all
  sudo: yes
  vars:
    - electrum_name: electrum-ltc
    - electrum_version: 3.1.3.1
    - electrum_bin: /usr/bin/electrum-ltc
    - exec_user: centos
    - database_dir: /home/centos/.electrum-ltc
    - download_url: https://codeload.github.com/pooler/{{ electrum_name }}/tar.gz/{{ electrum_version }} 
    - archive_file: /tmp/{{ electrum_name }}-{{ electrum_version }}.tar.gz
    - work_dir: /tmp/{{ electrum_name }}-{{ electrum_version }}
  roles:
    - devel
    - python3
    - electrum-ltc
    - electrum-wallet
  tasks:
    - name: systemd template setup
      template: src="templates/electrum-wallet.service.j2" dest="/etc/systemd/system/electrum-wallet.service" owner=root group=root
    - name: create database dir
      file: path={{ database_dir }} state=directory owner={{ exec_user }} group={{ exec_user }} mode=0700
    - name: create wallet dir
      file: path={{ database_dir }}/wallets state=directory owner={{ exec_user }} group={{ exec_user }} mode=0700
    - name: config template setup
      template: src="templates/config.j2" dest="{{ database_dir }}/config" owner={{ exec_user }} group={{ exec_user }}
