---
- hosts: all
  sudo: yes
  roles:
    - python3
    - devel
    - rockdb
    - electrumx
    - sslgen
  vars:
    - electrumx_version: 1.0.17
    - coin_name: Bitcoin
    - coind_host: localhost
    - coind_port: 8332
    - coind_user: bitcoin
    - coind_password: bitcoin123
    - exec_user: centos
    - database_dir: /home/centos/DB
    - tcp_port: 4444
    - ssh_port: 4445
    - max_send: 50000000
    - makejob: "{{ansible_processor_count}}"
  tasks:
    - name: create database dir
      file: path={{ database_dir }} state=directory owner={{ exec_user }} group={{ exec_user }} mode=0755
      
