---
- hosts: app
  sudo: yes
  roles:
    - python3
    - devel
    - rockdb
    - electrumx
  vars:
    - coin_name: "Litecoin"
    - coind_host: "localhost"
    - coind_port: "9332"
    - coind_user: "litecoin"
    - coind_password: "litecoin123"
    - database_dir: ""
