---
- hosts: test
  connection: docker
  remote_user: root
  sudo: yes
  roles:
    - python3
    - devel
    - rockdb
    - electrumx
    - sslgen
  vars:
    - electrumx_version: 1.0.17
    - coin_name: Monacoin
    - coind_host: localhost
    - coind_port: 9402
    - coind_user: monacoin
    - coind_password: monacoin123
    - exec_user: root
    - database_dir: /var/lib/electrumx_db
    - tcp_port: 4444
    - ssh_port: 4445
    - max_send: 50000000
    - makejob: "{{ansible_processor_count}}"
  tasks:
    - name: create database dir
      file: path={{ database_dir }} state=directory owner={{ exec_user }} group={{ exec_user }} mode=0755
      
