---
- name: download
  get_url: url=https://codeload.github.com/Bitcoin-sv/bitcoin-sv/tar.gz/v{{coind_version}} dest=/tmp mode=0440
- name: extract
  unarchive: src=/tmp/bitcoin-sv-{{coind_version}}.tar.gz dest=/tmp copy=no
- name: autogen
  command: scl enable devtoolset-7 "./autogen.sh" chdir=/tmp/bitcoin-sv-{{coind_version}}
- name: configure
  command: scl enable devtoolset-7 "./configure --disable-wallet --program-transform-name=s/bitcoin/bitcoinsv/g" chdir=/tmp/bitcoin-sv-{{coind_version}}
- name: make
  command: scl enable devtoolset-7 "make -j {{makejob}}" chdir=/tmp/bitcoin-sv-{{coind_version}}
- name: make install
  command: scl enable devtoolset-7 "make install" chdir=/tmp/bitcoin-sv-{{coind_version}}
- name: systemd template setup
  template: src="templates/coind.service.j2" dest="/etc/systemd/system/{{ coin_name }}.service" owner=root group=root
