---
- name: pip install
  pip: name={{ item }} executable=pip3.6
  with_items:
    - protobuf3
- name: download
  get_url: url={{ download_url }} dest=/tmp mode=0440
- name: extract
  unarchive: src={{ archive_file }} dest=/tmp copy=no
- name: protobuf
  command: protoc-gen-python3 --proto_path=lib/ --python_out=lib/ lib/paymentrequest.proto chdir={{ work_dir }}
- name: install
  command: /usr/bin/python3.6 setup.py install chdir={{ work_dir }}
