---
- hosts: all
  sudo: yes
  vars:
    - coin_name: bitcoincash
    - coin_rpcport: 7332
    - coind_version: 0.16.0
    - makejob: "{{ansible_processor_count}}"
  roles:
    - devel
    - gcc7
    - bitcoin-abc

