---
- hosts: all
  sudo: yes
  vars:
    - coin_name: bitcoincash
    - coin_rpcport: 7332
    - coind_version: 0.15.1
    - makejob: "{{ansible_processor_count}}"
  roles:
    - devel
    - bitcoin-abc

