---
- name: download
  get_url: url=https://codeload.github.com/dogecoin/dogecoin/tar.gz/v{{coind_version}} dest=/tmp mode=0440
- name: extract
  unarchive: src=/tmp/dogecoin-{{coind_version}}.tar.gz dest=/tmp copy=no
- name: autogen
  command: ./autogen.sh chdir=/tmp/dogecoin-{{coind_version}}
- name: configure
  command: ./configure --disable-wallet chdir=/tmp/dogecoin-{{coind_version}}
- name: make
  command: make -j {{makejob}} chdir=/tmp/dogecoin-{{coind_version}}
- name: make install
  command: make install chdir=/tmp/dogecoin-{{coind_version}}
- name: systemd template setup
  template: src="templates/coind.service.j2" dest="/etc/systemd/system/{{ coin_name }}.service" owner=root group=root
